#!/usr/bin/env bash

# Make various utils do color
export CLICOLOR=true

# Editor
export EDITOR=vim

# Larger bash history
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE

# Ignore duplicate commands and whitespace
export HISTCONTROL=ignoreboth

# Ignore some commands in the history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date"

# Prefer us english and utf-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Programming Stuff
export PYTHONIOENCODING='UTF-8';
export MAVEN_OPTS="-Xmx4096m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:MaxTenuringThreshold=5"

# Enable colored grep output
export GREP_OPTIONS='--color=auto'

# Common less options
export LESS="-iMRFX"
